### ISSUE TITLE
[Request] Glossary support

### ISSUE THREAD

**Issue by unicode45** [HeyHeyChicken/DeepL-File-Translator#1]
Hi,
Are you planning to support selecting glossary_id when using deepl API?

**Comment by HeyHeyChicken** [comment]
Hi,
If I understood correctly, you want to choose the language in the HMI right?

**Comment by unicode45** [comment]
Deepl can perform translations with a glossary which contains pre-registered terms.
This is especially useful when translating with proper nouns.

You can find more information about the glossary feature below.
https://support.deepl.com/hc/en-us/articles/360021634540-About-glossaries

Btw, It'll be great if I can target language in the HMI, too.

**Comment by HeyHeyChicken** [comment]
Ok, I just understood.
I don't think I'll be working on this application soon.
I'm on other projects at the moment... But you have the possibility to fork it :)
